### PR TITLE
Reduce manual work – Issue #11

### PR DESCRIPTION
**Pull request by macwinnie**

### CODE REVIEW

**Comment by DracoBlue** [comment]
Any chance to make the persistence adapter and sqlite path configurable, too?

IMHO it would be great to use either dsn (mysql://) for database configuration or prefix with DATABASE_ to make sqlite or psql possible, too :).

**Comment by macwinnie** [comment]
I think, [Phinx](https://phinx.org/) supports those database types as well – for the shared-secrets app, changes would have to be implemented and applied ... // @yahesh

**Comment by jonico** [comment]
Love the propose changes. When I [adapted](https://github.com/jonico/shared-secrets) the service for the [PlanetScale Pull Request Integration](https://github.com/jonico/pscale-cli-helper-scripts) - I wished that functionality was already present.

If merging all at once in one PR is too much, I'd propose to split the possibility to configure with environment variables and the docker compose / Phinx part.

**Comment by yahesh** [comment]
Unfortunately, this PR mixes three different features:
* support for environment variables (which has since been implemented without requiring 3rd party dependencies
* dependency on composer and phinx to auto-create the MySQL table
* example for a docker-compose file

**Comment by weizenspreu** [comment]
Won't happen here. New fork is over at https://github.com/yahesh/shared-secrets

**Pull request closed without merging**
